name: Bug Report
description: |
  File a bug report to be fixed.

  Sponsors get priority issues, PRs, fixes and requests. Not a sponsor? [You're a just click away!](https://github.com/sponsors/DarkGhostHunter).
title: "[X.x] What does happen that is considered an error or bug?"
labels: ["bug"]
assignees:
  - DarkGhostHunter
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        The more detailed this bug report is, the faster it can be reviewed and fixed.
  - type: input
    id: version-php-os
    attributes:
      label: PHP & Platform
      description: Exact PHP and Platform (OS) versions using this package.
      placeholder: 8.1.2 - Ubuntu 22.04 x64
    validations:
      required: true
  - type: input
    id: version-db
    attributes:
      label: Database
      description: Exact DB version using this package, if applicable.
      placeholder: MySQL 8.0.28
    validations:
      required: false
  - type: input
    id: version-laravel
    attributes:
      label: Laravel version
      description: Exact Laravel version using this package.
      placeholder: 9.2.3
    validations:
      required: true
  - type: checkboxes
    id: requirements
    attributes:
      label: Have you done this?
      options:
        - label: I have checked my logs and I'm sure is a bug in this package.
          required: true
        - label: I can reproduce this bug in isolation (vanilla Laravel install)
          required: true
        - label: I can suggest a workaround as a Pull Request
          required: false
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: Write what you expect to (correctly) happen.
      placeholder: When I do this, I expect to happen that.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write what (incorrectly) happens instead.
      placeholder: Instead, when I do this, I receive that.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Paste the code to assert in a test, or just comment with the repository with the bug to download.
      render: php
      placeholder: |
        $test = Laragear::make()->break();

        static::assertFalse($test);

        // or comment with "https://github.com/my-name/my-bug-report"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Stack trace & logs
      description: If you have a **full** stack trace, you can copy it here. You may hide sensible information.
      placeholder: This is automatically formatted into code, no need for ``` backticks.
      render: shell
    validations:
      required: false
